version: 0.1

phases:
  build:
    commands:
      - sh ./gradlew --no-daemon test shadowJar
      - aws cloudformation package --template-file sam_template.yml --s3-bucket tbone-skill --s3-prefix builds --output-template-file new_sam_template.yml

artifacts:
  files:
    - new_sam_template.yml
