AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sad T-Bone Alexa skill
Resources:
  tbonePlayWaWa:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: tbone.TboneSpeechletRequestStreamHandler
      Runtime: java8
      CodeUri: ./build/libs/tbone-all.jar
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::937638153365:role/tbone-skill-lambda-role'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
