AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  tbonePlayWaWa:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: tbone.TboneSpeechletRequestStreamHandler
      Runtime: java8
      CodeUri: ./
      Description: 'Backs the Sad T-Bone Alexa skill'
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::937638153365:role/service-role/tbone-prod'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
