application:
  supportedIds:
    - amzn1.ask.skill.7df230ef-4a94-43b4-86cc-6b347a5a3a42 # test
    - amzn1.ask.skill.aedee7a9-f813-4a4d-bf10-ddf8e2e0eb6e # prod

audio:
  prefix: https://d3bopkxu4xdpre.cloudfront.net/audio
  fileNames:
    - audio_1.mp3
    - audio_2.mp3
    - audio_3.mp3
    - audio_4.mp3